version: "3"

services:
    db:
#            dockerfile: ./db/Dockerfile
#        image: mysql:8.0.23
#        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
#            - "./db-dumps:/tmp/db-dumps"
#            - "./dev-ops:/tmp/dev-ops"
        build:
            context: ./db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - "../symfony:/var/www/symfony/"
#            - "../Makefile:/var/www/html/Makefile"
#            - "../docker/db-dumps:/var/www/html/db-dumps/"
#            - "../docker/dev-ops:/var/www/html/dev-ops/"
        networks:
            - symfony
    nginx:
        build:
            context: ./nginx
        volumes:
            - "../symfony:/var/www/symfony/"
#            - "../Makefile:/var/www/html/Makefile"
#            - "../docker/db-dumps:/var/www/html/db-dumps"
#            - "../docker/dev-ops:/var/www/html/dev-ops"
        ports:
            - 80:80
        networks:
            - symfony
        env_file:
            - .env.nginx.local

volumes:
#    symfony_dockerized_app_sync:
#        external: true
    db_app:

networks:
    symfony:
